version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shary_postgres
    environment:
      POSTGRES_DB: shary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1"
    ports:
      - "5477:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 